In [52]:
import numpy as np
import pandas as pd
from keras.models import Sequential

from keras.layers import Dense
from keras.layers import Embedding
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold 
from keras.optimizers import SGD
from keras.constraints import maxnorm
# Modelling Helpers :
from sklearn.preprocessing import Imputer , Normalizer , scale
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.feature_selection import RFECV
from sklearn.model_selection import GridSearchCV , KFold , cross_val_score
# Deep Learning Libraries
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
from keras.optimizers import Adam,SGD,Adagrad,Adadelta,RMSprop
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.sequence import pad_sequences
from keras.callbacks import ReduceLROnPlateau, LearningRateScheduler
from keras.utils import to_categorical
from keras import backend as K
K.set_image_dim_ordering('th')


In [3]:
#Load the data set from Keras IMDB
from keras.datasets import imdb


In [4]:
(X_train,Y_train),(X_test,Y_test) = imdb.load_data()

17465344/17464789 [==============================] - 75s 4us/step


In [8]:
X_train.shape,Y_train.shape,X_test.shape,Y_test.shape

((25000,), (25000,), (25000,), (25000,))

In [9]:
X = np.concatenate((X_train,X_test),axis=0)
Y = np.concatenate((Y_train,Y_test),axis=0)

In [11]:
X.shape,Y.shape

((50000,), (50000,))

In [17]:
(np.unique(Y))

array([0, 1])

In [13]:
Y

array([1, 0, 0, ..., 0, 0, 0])

In [16]:
pd.unique(Y)

array([1, 0])

In [22]:
np.hstack(X)

array([   1,   14,   22, ...,   34, 2005, 2643])

In [29]:
print("Number of Words: %d" %(len(np.unique(np.hstack(X)))))

Number of Words: 88585


In [97]:
top_words = 5000
(X_train,Y_train),(X_test,Y_test) =imdb.load_data(nb_words= top_words)

/home/sola/anaconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/keras/datasets/imdb.py:49: UserWarning: The `nb_words` argument in `load_data` has been renamed `num_words`.
  warnings.warn('The `nb_words` argument in `load_data` '


In [98]:
from keras.preprocessing.sequence import sequence
# X_train = sequence.pad_Sequences(X_train,maxlen=500)

In [99]:
max_words = 500

In [100]:
X_train = sequence.pad_sequences(X_train,maxlen = max_words)

In [101]:
X_test = sequence.pad_sequences(X_test,maxlen = max_words)

In [102]:
#Create model
model = Sequential()
model.add(Embedding(top_words,32,input_length = max_words))
model.add(Flatten())
model.add(Dense(250,activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [103]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),nb_epoch=2,batch_size=128,verbose=1)


/home/sola/anaconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 25000 samples, validate on 25000 samples
Epoch 1/2
25000/25000 [==============================] - 18s 711us/step - loss: 0.5067 - acc: 0.7234 - val_loss: 0.3271 - val_acc: 0.8574
Epoch 2/2
25000/25000 [==============================] - 18s 709us/step - loss: 0.1910 - acc: 0.9279 - val_loss: 0.2997 - val_acc: 0.8747


In [105]:
scores = model.evaluate(X_test,Y_test,verbose=0)

In [108]:
print("Accuracy:%.2f" %(scores[1]*100) )

Accuracy:87.47


In [110]:
#Build Convolution Networks
seed = 7
np.random.seed(seed)

In [111]:
from keras.layers.convolutional import Convolution1D
from keras.layers.convolutional import MaxPooling1D

In [114]:
model = Sequential()
model.add(Embedding(top_words,32,input_length=max_words))
model.add(Convolution1D(nb_filter=32,filter_length=3,border_mode='same',activation='relu'))
model.add(MaxPooling1D(pool_length=2))
model.add(Flatten())
model.add(Dense(250,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


/home/sola/anaconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="relu", filters=32, kernel_size=3, padding="same")`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/sola/anaconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(pool_size=2)`
  after removing the cwd from sys.path.


In [116]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [117]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),nb_epoch=2,batch_size=128,verbose=1)

/home/sola/anaconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 25000 samples, validate on 25000 samples
Epoch 1/2
25000/25000 [==============================] - 19s 745us/step - loss: 0.4389 - acc: 0.7712 - val_loss: 0.2782 - val_acc: 0.8841
Epoch 2/2
25000/25000 [==============================] - 19s 766us/step - loss: 0.2182 - acc: 0.9154 - val_loss: 0.2775 - val_acc: 0.8858


In [119]:
scores = model.evaluate(X_test,Y_test,verbose=0)

In [121]:
print("Accuracy:%.2f" %(scores[1]*100))

Accuracy:88.58


In [125]:
#